getwd()
nodes<-read.csv("Class-bench_partners (Nodes).csv")
head(nodes)
edges<-read.csv("Class-bench_partners (Edges).csv")
head(edges)
net<-graph.data.frame(d=edges,vertices=nodes,directed=T)
get.adjacency(net)
plot(net)
vcount(net)
ecount(net)
density<-ecount(net)/(vcount(net)* vcount(net)-1)
density
degree(net)
reciprocity(net)
transitivity(net)
centralization.degree(net)
centralization.closeness(net)
centralization.betweenness(net)
centralization.evcent(net)
cluster_spinglass(net)

